### ISSUE TITLE
Link for final exam doodle

### ISSUE THREAD

**Issue by wpedrak** [janchorowski/ml_uwr#10]
There was a link to doodle about the term of the final exam. It would be nice to have it somewhere in the repo.

**Comment by janchorowski** [comment]
an yo umake a PR wiith a copy of it from SKOS to somewhere appropriate (readme?  important anouncements.md?)

**Comment by wpedrak** [comment]
My real problem was that I didn't spot the link on SKOS. Anyway, PR it is (https://github.com/janchorowski/ml_uwr/pull/11).
