### ISSUE TITLE
Expand Adaboost notes

### ISSUE THREAD

**Issue by janchorowski** [janchorowski/ml_uwr#5]
Expand [Adaboost notes](https://github.com/janchorowski/ml_uwr/blob/fall2019/lectures/05_adabost_demo.ipynb) with sections for bonus points:
- [ ] Adaboost derivation, 2bp [handnotes](https://drive.google.com/open?id=0B5j9vIO_NjwcLVdPdUF1cU1EOHJoTExiZzZTOE40SnBHMFE4)
- [ ] Adaboost proof, 2bp, handnotes + [proof](https://www.cs.princeton.edu/courses/archive/fall07/cos402/readings/boosting.pdf)
- [ ] Cooler demo 1-2bp
- [ ] [Viola Jones](https://en.wikipedia.org/wiki/Viola%E2%80%93Jones_object_detection_framework) [paper](https://drive.google.com/file/d/1wsJwbl56FdTPYwNPdxhWTjjkoOW70OL5/view?usp=sharing) w 1bp face detector

**Comment by PBPZA** [comment]
I will do it.
